export { default as Blog} from './blog/Blog';
export { default as Features} from './features/Features';
export { default as Footer} from './footer/Footer';
export { default as Header} from './header/Header';
export { default as Login} from './login/Login';
export { default as Register} from './register/Register';
export { default as Toggle} from './themeToggle/Toggle';
export { default as Forgot} from './password/Forgot';
export { default as Dashboard} from './dashboard/Dashboard';